import type { ProductRecord } from '../types'
import type { ComplianceReport } from './rules'

const OWNER_LABEL: Record<string, string> = {
  design: 'Design',
  'compliance-uk-eu': 'Compliance UK/EU',
  'us-regulatory': 'US regulatory',
  formulation: 'Formulation',
  client: 'Client',
  account: 'Account',
  ops: 'Ops',
}

/**
 * Emit `compliance-findings.md` in exactly the shape claims-and-warning-check
 * specifies, so the output drops straight into a project folder.
 */
export function toFindingsMarkdown(p: ProductRecord, r: ComplianceReport): string {
  const date = r.generatedAt.slice(0, 10)
  const head = [
    `# Compliance findings — ${p.brand} ${p.productName} — ${r.market} — ${date}`,
    '',
    `Reviewer requested: ${r.reviewer}`,
    `Artwork record: ${p.format} · stage ${p.stage}`,
    `Formulation version: ${p.formulationVersion || '**MISSING**'}`,
    '',
    `**${r.headline}**`,
    '',
    `Verdict: **${r.verdict}** · Blockers: ${r.counts.BLOCKER} · Major: ${r.counts.MAJOR} · Minor: ${r.counts.MINOR} · Questions: ${r.counts.QUESTION}`,
    '',
  ]

  const table = [
    '| # | Area | Finding | Severity | Proposed fix | Owner |',
    '|---|---|---|---|---|---|',
    ...r.findings.map(
      (f) =>
        `| ${f.id} | ${f.area} | ${esc(f.finding)} | ${f.severity} | ${esc(f.proposedFix)} | ${OWNER_LABEL[f.owner] ?? f.owner} |`,
    ),
  ]

  const questions = r.findings.filter((f) => f.severity === 'QUESTION' || f.severity === 'BLOCKER')
  const byArea = new Map<string, typeof questions>()
  for (const q of questions) {
    if (!byArea.has(q.area)) byArea.set(q.area, [])
    byArea.get(q.area)!.push(q)
  }

  const AREA_TITLES: Record<string, string> = {
    A: 'A · Classification and panel type',
    B: 'B · Ingredient deck',
    C: 'C · Mandatory statements',
    D: 'D · Claims',
    E: 'E · Language and typography',
  }

  const sheet = ['', '## Question sheet for the reviewer', '']
  if (!questions.length) {
    sheet.push('Nothing to route. No blockers and no open questions.')
  } else {
    for (const area of ['A', 'B', 'C', 'D', 'E']) {
      const qs = byArea.get(area)
      if (!qs?.length) continue
      sheet.push(`### ${AREA_TITLES[area]}`, '')
      qs.forEach((q, i) => {
        sheet.push(`${i + 1}. **${q.id}** — ${q.finding}`)
        sheet.push(`   *Why it matters:* ${q.rationale}`)
        sheet.push(`   *Proposed:* ${q.proposedFix} — ${OWNER_LABEL[q.owner] ?? q.owner}`)
        sheet.push('')
      })
    }
  }

  const notes = ['', '## Market notes', '', ...r.marketNotes.map((n) => `- ${n}`)]

  const footer = [
    '',
    '---',
    '',
    '*Generated by SF Pack AI. This file finds problems and frames questions; it does not issue the regulatory opinion.*',
    `*That belongs to ${r.reviewer}.*`,
    '',
  ]

  return [...head, ...table, ...sheet, ...notes, ...footer].join('\n')
}

const esc = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ')
